### ISSUE TITLE
Compiling on Ubuntu 15.04

### ISSUE THREAD

**Issue by RoelofBerg** [UDOOboard/Kernel_Unico#16]
On Ubuntu 15.04 and UDOO NEO if see the compile error:
**No rule to make target `drivers/rtc/class.o', needed by`drivers/rtc/rtc-core.o'. Stop.**
I followed: http://www.udoo.org/docs/Advanced_Setup/Compile_The_Linux_Kernel_And_The_Modules 

(And by the way, I used Ubuntu's cross compiler, because the one provided on above's UDOO website isn't compatible to recent 64 bit Ubuntu systems. I did so by apt-get install gcc-arm-linux-gnueabi and then using CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- . Using a generic compiler is ok for me, because it's only for a training.)

Then on the step
make ARCH=arm menuconfig
I disabled DeviceDrivers/RealtimeClock

Then it compiles ... at least ...

**Comment by patrykk** [comment]
hi,
please use repo linux_kernel from :
https://github.com/UDOOboard/linux_kernel
This kernel is not for udoo neo.

issue to close.

best regards,

**Comment by RoelofBerg** [comment]
Then I shouldn't wonder :)
(For UDOO neo I'm following now: http://www.udoo.org/docs-neo/Kernel_Hacking/Compile_the_kernel.html)

However, what I reported might still be an issue when someone wants to build an original UDOO version's kernel on Ubuntu 15.4. and if the RTC isn't vital (is it?), this might be a workaround.

However, I'm moving to the correct kernel now. Thanks.
